### BEGIN AppDBInstance resources ###
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: appdbinstances.ctl.isla.solutions
spec:
  group: ctl.isla.solutions
  version: v1
  scope: Namespaced
  names:
    plural: appdbinstances
    singular: appdbinstance
    kind: AppDBInstance
    shortNames: ["appdbi"]
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: appdb-instance-operator
spec:
  generateSelector: true
  resyncPeriodSeconds: 10
  parentResource:
    apiVersion: ctl.isla.solutions/v1
    resource: appdbinstances
  childResources:
  - apiVersion: v1
    resource: secrets
  - apiVersion: v1
    resource: services
  - apiVersion: apps/v1beta1
    resource: deployments
  - apiVersion: ctl.isla.solutions/v1
    resource: terraformapplys
  - apiVersion: ctl.isla.solutions/v1
    resource: terraformplans
  hooks:
    sync:
      webhook:
        url: http://appdb-instance-operator.metacontroller/sync
### END AppDBInstance resources ###
---
### BEGIN AppDB resources ###
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: appdbs.ctl.isla.solutions
spec:
  group: ctl.isla.solutions
  version: v1
  scope: Namespaced
  names:
    plural: appdbs
    singular: appdb
    kind: AppDB
    shortNames: ["appdb"]
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: appdb-operator
spec:
  generateSelector: true
  resyncPeriodSeconds: 10
  parentResource:
    apiVersion: ctl.isla.solutions/v1
    resource: appdbs
  childResources:
  - apiVersion: v1
    resource: secrets
  - apiVersion: batch/v1
    resource: jobs
    updateStrategy:
      method: InPlace
  - apiVersion: ctl.isla.solutions/v1
    resource: terraformapplys
    updateStrategy:
      method: InPlace
  - apiVersion: ctl.isla.solutions/v1
    resource: terraformplans
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://appdb-operator.metacontroller/sync
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: appdb-operator
  namespace: metacontroller
  labels:
    app: appdb-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appdb-operator
  template:
    metadata:
      labels:
        app: appdb-operator
    spec:
      serviceAccountName: appdb-operator
      containers:
      - name: appdb-instance-operator
        image: gcr.io/cloud-solutions-group/appdb-operator:0.1.1
        imagePullPolicy: Always
        command: ["/usr/bin/appdb-instance-operator"]
        env:
        - name: TF_IMAGE
          value: gcr.io/cloud-solutions-group/terraform-pod:v0.11.8
        - name: TF_IMAGE_PULL_POLICY
          value: Always
        - name: CLOUD_SQL_PROXY_IMAGE
          value: gcr.io/cloudsql-docker/gce-proxy:1.11
        # - name: HTTP_DEBUG
        #   value: "true"
      - name: appdb-operator
        image: gcr.io/cloud-solutions-group/appdb-operator:0.1.1
        imagePullPolicy: Always
        command: ["/usr/bin/appdb-operator"]
        env:
        - name: TF_IMAGE
          value: gcr.io/cloud-solutions-group/terraform-pod:v0.11.8
        - name: TF_IMAGE_PULL_POLICY
          value: Always
        # - name: HTTP_DEBUG
        #   value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: appdb-instance-operator
  namespace: metacontroller
spec:
  type: ClusterIP
  ports:
  - name: appdb
    port: 80
    targetPort: 8080
  selector:
    app: appdb-operator
---
apiVersion: v1
kind: Service
metadata:
  name: appdb-operator
  namespace: metacontroller
spec:
  type: ClusterIP
  ports:
  - name: appdb
    port: 80
    targetPort: 8081
  selector:
    app: appdb-operator
### END AppDB resources ###